### ISSUE TITLE
can't use onion or cjdns --address

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-device-address#3]
```
cryptix@apu42:~$ ./scuttlebot/bin.js deviceAddress.announce --address jymslegna3xmlrdk.onion --availability 0.9


/home/cryptix/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error: not a valid address:jymslegna3xmlrdk.onion
    at /home/cryptix/.ssb/node_modules/ssb-device-address/index.js:92:21
    at /home/cryptix/.ssb/node_modules/ssb-device-address/index.js:79:9
    at onReady (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:67:15)
    at Object.getAddress (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:78:7)
    at Object.announce (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:83:12)
    at Object.hooked (/home/cryptix/scuttlebot/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/cryptix/scuttlebot/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/cryptix/scuttlebot/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/cryptix/scuttlebot/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/cryptix/scuttlebot/node_modules/packet-stream/index.js:161:17)

cryptix@apu42:~$ ./scuttlebot/bin.js deviceAddress.announce --address fc4c:743b:691e:c2aa:276e:d214:d557:3055 --availability 0.7

/home/cryptix/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error: not a valid address:fc4c:743b:691e:c2aa:276e:d214:d557:3055
    at /home/cryptix/.ssb/node_modules/ssb-device-address/index.js:92:21
    at /home/cryptix/.ssb/node_modules/ssb-device-address/index.js:79:9
    at onReady (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:67:15)
    at Object.getAddress (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:78:7)
    at Object.announce (/home/cryptix/.ssb/node_modules/ssb-device-address/index.js:83:12)
    at Object.hooked (/home/cryptix/scuttlebot/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/cryptix/scuttlebot/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/cryptix/scuttlebot/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/cryptix/scuttlebot/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/cryptix/scuttlebot/node_modules/packet-stream/index.js:161:17)

```

**Comment by cryptix** [comment]
So on that line it just passes the host/domain string to ssb-ref right?

https://github.com/ssbc/ssb-device-address/blob/b2bc7c6d35d29d614a2c75e62cab9ccabd36d8a3/index.js#L91

I see tests for onion/cjdns in ssb-ref but they all have a pubkey at the end. Not sure what to do here...

**Comment by cryptix** [comment]
Okay. It works when I construct the full multi address by hand (so `net:address~shs:edkeywithoutsiglorsuffix`).

**Comment by dominictarr** [comment]
yes it must be a multiserver address.
